# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1294e00e2db06c02daaf037aee63533c74f2296387f953901253ce8066d16c6428081fb8d0592c754b1a1bc17356fcc7d1c2c6a15029aca8a2e9e15da0504f0

test:
  secret_key_base: a70585720325a22766a0768fa1d918d4c1a4ca248962213853ee6c5ad403f38b9728e0dd219dee638fcf35146bfb5777babc8069e9f5294b210155eaf5ed9846

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
